default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  host: localhost
  username: ubuntu
  password: kite

development:
  <<: *default
  database: my_kite_shop_production

test:
  <<: *default
  database: my_kite_shop_test

production:
  primary: &primary_production
    <<: *default
    database: my_kite_shop_production
  cache:
    <<: *primary_production
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    migrations_paths: db/cable_migrate
